### PR TITLE
Only get cache

### PR DESCRIPTION
**Pull request by daemonl**
This change is [Reviewable](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/10)

### CODE REVIEW

**Review by RickyCook — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/10)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @daemonl)

___
*[main.go, line 172 at r1](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/10#-Lpfih008cq7J9l3Qu4j:-Lpfih01DaHmv6fCrgSc:b-nvmd1q) ([raw file](https://github.com/dutyofcare/spa-version-proxy/blob/fbb1c015ee0f369ceaa73c84cd2a74a4812d80eb/main.go#L172)):*
> ```Go
> 
> func (fs fileServer) ServeHTTP(rw http.ResponseWriter, req *http.Request) {
> 	if req.Method != "GET" {
> ```

do we need to allow `OPTIONS` as well, for XHR?

**Review by daemonl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/10)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @RickyCook)

___
*[main.go, line 172 at r1](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/10#-Lpfih008cq7J9l3Qu4j:-LpfkY_-8_mp-xKoNEnK:b-dnbfvm) ([raw file](https://github.com/dutyofcare/spa-version-proxy/blob/fbb1c015ee0f369ceaa73c84cd2a74a4812d80eb/main.go#L172)):*
<details><summary><i>Previously, RickyCook (Ricky Cook) wrote…</i></summary><blockquote>

do we need to allow `OPTIONS` as well, for XHR?
</blockquote></details>

I was thinking about it, that should be done elsewhere as a separate middleware if we did (doesn't need to know about the cache), however this will not apply to the dev proxy, only to the static pages, so XHR Options requests shouldn't happen, and the currently deployed app.dutyof.care rejects OPTIONS requests - so nothing is currently making a request for it. - the register page hits `https://app.dutyof.care/api/register` for OPTIONS, which will still respond correctly.

**Review by RickyCook — APPROVED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/10)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[main.go, line 172 at r1](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/10#-Lpfih008cq7J9l3Qu4j:-LpfmWKk5I-nybqa_IAg:b-2ywt8u) ([raw file](https://github.com/dutyofcare/spa-version-proxy/blob/fbb1c015ee0f369ceaa73c84cd2a74a4812d80eb/main.go#L172)):*
<details><summary><i>Previously, daemonl (Damien Whitten) wrote…</i></summary><blockquote>

I was thinking about it, that should be done elsewhere as a separate middleware if we did (doesn't need to know about the cache), however this will not apply to the dev proxy, only to the static pages, so XHR Options requests shouldn't happen, and the currently deployed app.dutyof.care rejects OPTIONS requests - so nothing is currently making a request for it. - the register page hits `https://app.dutyof.care/api/register` for OPTIONS, which will still respond correctly.
</blockquote></details>

yeah that may be getting into more HAR storage rather than just raw data storage too

**Review by daemonl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/10)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[main.go, line 172 at r1](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/10#-Lpfih008cq7J9l3Qu4j:-Lpfn0FN64_9wpDANHRC:b-n2xj8n) ([raw file](https://github.com/dutyofcare/spa-version-proxy/blob/fbb1c015ee0f369ceaa73c84cd2a74a4812d80eb/main.go#L172)):*
<details><summary><i>Previously, RickyCook (Ricky Cook) wrote…</i></summary><blockquote>

yeah that may be getting into more HAR storage rather than just raw data storage too
</blockquote></details>

If I was doing it, would more likely just implement CORS here (based on config) rather than attempt to proxy it to what is *supposed* to be a static file server, especially given the complexity of matching request domains to the upstream

**Pull request merged**
