### PR TITLE
Docker

### PR DESCRIPTION
**Pull request by daemonl**
Configuration at https://hub.docker.com/r/dutyofcare/spa-version-proxy should be taken as part of this PR.

---
This change is [Reviewable](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/6)

### CODE REVIEW

**Review by RickyCook — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/6)* status: all files reviewed, 1 unresolved discussion (waiting on @daemonl)

___
*[Dockerfile, line 4 at r1](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/6#-Lpa0QAgDoByLVwAlYTw:-Lpa0QAgDoByLVwAlYTx:b5oukxr) ([raw file](https://github.com/dutyofcare/spa-version-proxy/blob/13a76cf15d137e575a5888648496c7c2832ba832/Dockerfile#L4)):*
> ```Dockerfile
> COPY *.go ./
> RUN go test *.go
> RUN go build -o /proxy-server ./main.go
> ```

id go multi-stage; this container doesn't need the go compiler in it... should only be like a <5mb alpine container or something

**Review by daemonl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/6)* status: all files reviewed, 1 unresolved discussion (waiting on @RickyCook)

___
*[Dockerfile, line 4 at r1](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/6#-Lpa0QAgDoByLVwAlYTw:-Lpa1wbXAyCujFMdkqrx:b-mmn2cc) ([raw file](https://github.com/dutyofcare/spa-version-proxy/blob/13a76cf15d137e575a5888648496c7c2832ba832/Dockerfile#L4)):*
<details><summary><i>Previously, RickyCook (Ricky Cook) wrote…</i></summary><blockquote>

id go multi-stage; this container doesn't need the go compiler in it... should only be like a <5mb alpine container or something
</blockquote></details>

Can we add that as an enhancement later? It's not just as simple as the base alpine, copy binary, it needs CA certificates and some extra flags on the go build to make it not assume standard C library stuff

**Review by daemonl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/6)* status: all files reviewed, 1 unresolved discussion (waiting on @RickyCook)

___
*[Dockerfile, line 4 at r1](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/6#-Lpa0QAgDoByLVwAlYTw:-Lpa5jMBEPLj9FUNNSvG:bcu09ez) ([raw file](https://github.com/dutyofcare/spa-version-proxy/blob/13a76cf15d137e575a5888648496c7c2832ba832/Dockerfile#L4)):*
<details><summary><i>Previously, daemonl (Damien Whitten) wrote…</i></summary><blockquote>

Can we add that as an enhancement later? It's not just as simple as the base alpine, copy binary, it needs CA certificates and some extra flags on the go build to make it not assume standard C library stuff
</blockquote></details>

NM, I'll do it, I have nothing else to do while we argue about the others :-)

**Review by RickyCook — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/6)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by RickyCook — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/6)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
