### PR TITLE
Basic Cache and Version

### PR DESCRIPTION
**Pull request by daemonl**
Basic cacher and versioner.

---
This change is [Reviewable](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/1)

### CODE REVIEW

**Review by RickyCook — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/1)* status: all files reviewed, 4 unresolved discussions (waiting on @daemonl)

___
*[main.go, line 92 at r1](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/1#-Lp_ihM55h4Zn_A19FMY:-Lp_ihM55h4Zn_A19FMZ:bnh502l) ([raw file](https://github.com/dutyofcare/spa-version-proxy/blob/da859263acb10acbb37d128c8d2864435111ea67/main.go#L92)):*
> ```Go
> 
> 	//  Taken from http.Dir.Open
> 	if filepath.Separator != '/' && strings.ContainsRune(name, filepath.Separator) {
> ```

why `!= '/'`?
___
*[main.go, line 95 at r1](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/1#-Lp_jODJANzazlF5iuFT:-Lp_jODJANzazlF5iuFU:b55us3w) ([raw file](https://github.com/dutyofcare/spa-version-proxy/blob/da859263acb10acbb37d128c8d2864435111ea67/main.go#L95)):*
> ```Go
> 		return errors.New("http: invalid character in file path")
> 	}
> 	fullName := filepath.Join(string(fs.root), filepath.FromSlash(path.Clean("/"+name)))
> ```

`filepath.Separator + name`?
___
*[main.go, line 98 at r1](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/1#-Lp_k2M_3wiO3Q0sL6dX:-Lp_k2M_3wiO3Q0sL6dY:bpofgi) ([raw file](https://github.com/dutyofcare/spa-version-proxy/blob/da859263acb10acbb37d128c8d2864435111ea67/main.go#L98)):*
> ```Go
> 	// Done with http.Dir.Open clone
> 
> 	os.MkdirAll(filepath.Dir(fullName), os.FileMode(0770))
> ```

not 0755?

also, surely the 0 is stripped here? just to match convention?
___
*[main.go, line 124 at r1](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/1#-Lp_ke-UE6U2-9_YpZAE:-Lp_ke-VAz-MgaLu_SNg:b65m6if) ([raw file](https://github.com/dutyofcare/spa-version-proxy/blob/da859263acb10acbb37d128c8d2864435111ea67/main.go#L124)):*
> ```Go
> 	defer parsedResponse.Body.Close()
> 
> 	// TODO: Discard and delete if cache is expired.
> ```

should it ever expire? the content is immutable

**Review by daemonl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/1)* status: all files reviewed, 4 unresolved discussions (waiting on @RickyCook)

___
*[main.go, line 92 at r1](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/1#-Lp_ihM55h4Zn_A19FMY:-Lp_lTuJ3BDvpOFbXNdM:b-f3jhxz) ([raw file](https://github.com/dutyofcare/spa-version-proxy/blob/da859263acb10acbb37d128c8d2864435111ea67/main.go#L92)):*
<details><summary><i>Previously, RickyCook (Ricky Cook) wrote…</i></summary><blockquote>

why `!= '/'`?
</blockquote></details>

If windows.
___
*[main.go, line 95 at r1](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/1#-Lp_jODJANzazlF5iuFT:-Lp_loI-BfWwFYUUnZ-i:b-ip0lo7) ([raw file](https://github.com/dutyofcare/spa-version-proxy/blob/da859263acb10acbb37d128c8d2864435111ea67/main.go#L95)):*
<details><summary><i>Previously, RickyCook (Ricky Cook) wrote…</i></summary><blockquote>

`filepath.Separator + name`?
</blockquote></details>

Is complicated at this point, it won't actually *work* on windows, because it all assumes the directory structure matches the URL path structure. (or... it will create a flat structure with files which have '/' in them? IDK windows)

path.Clean takes a URL style path, so in this case it should be the URL separator, but it should be the filesystem path separator when joining to the root (which it will be)
___
*[main.go, line 98 at r1](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/1#-Lp_k2M_3wiO3Q0sL6dX:-Lp_lgIJ3I_ELkn1UkiC:b-8m5e5) ([raw file](https://github.com/dutyofcare/spa-version-proxy/blob/da859263acb10acbb37d128c8d2864435111ea67/main.go#L98)):*
<details><summary><i>Previously, RickyCook (Ricky Cook) wrote…</i></summary><blockquote>

not 0755?

also, surely the 0 is stripped here? just to match convention?
</blockquote></details>

0770 != 770, and this matches the defaults in `os.Create`
___
*[main.go, line 124 at r1](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/1#-Lp_ke-UE6U2-9_YpZAE:-Lp_mHUm9vgae4Bx8_zI:be0fbvj) ([raw file](https://github.com/dutyofcare/spa-version-proxy/blob/da859263acb10acbb37d128c8d2864435111ea67/main.go#L124)):*
<details><summary><i>Previously, RickyCook (Ricky Cook) wrote…</i></summary><blockquote>

should it ever expire? the content is immutable
</blockquote></details>

Theoretically immutable, but in practice possibly not. I've raised an issue for it, can discuss there. Do you want me to remove the TODO based on the issue?

**Review by RickyCook — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/1)* status: all files reviewed, 3 unresolved discussions (waiting on @daemonl)

___
*[main.go, line 92 at r1](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/1#-Lp_ihM55h4Zn_A19FMY:-Lpa2ncaBIhVdp0xuF5y:bs0ljw6) ([raw file](https://github.com/dutyofcare/spa-version-proxy/blob/da859263acb10acbb37d128c8d2864435111ea67/main.go#L92)):*
<details><summary><i>Previously, daemonl (Damien Whitten) wrote…</i></summary><blockquote>

If windows.
</blockquote></details>

i get that, but if you remove the conditional, there's no problem right? like no matter what, you just want to ensure that the name doesn't contain the path sep of your platform, and it doesn't matter if it's windows, nix, or anything else
___
*[main.go, line 95 at r1](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/1#-Lp_jODJANzazlF5iuFT:-Lpa3eps3JOF6A3pvrwx:bmdz8jr) ([raw file](https://github.com/dutyofcare/spa-version-proxy/blob/da859263acb10acbb37d128c8d2864435111ea67/main.go#L95)):*
<details><summary><i>Previously, daemonl (Damien Whitten) wrote…</i></summary><blockquote>

Is complicated at this point, it won't actually *work* on windows, because it all assumes the directory structure matches the URL path structure. (or... it will create a flat structure with files which have '/' in them? IDK windows)

path.Clean takes a URL style path, so in this case it should be the URL separator, but it should be the filesystem path separator when joining to the root (which it will be)
</blockquote></details>

id suggest that we either explicitly dont support windows (my preference), or figure out what it does since it could be a security issue. i wouldnt say this should block this PR, but we should decide
___
*[main.go, line 98 at r1](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/1#-Lp_k2M_3wiO3Q0sL6dX:-Lpa4bLe9JO7AjlLRSnT:b1vx9n2) ([raw file](https://github.com/dutyofcare/spa-version-proxy/blob/da859263acb10acbb37d128c8d2864435111ea67/main.go#L98)):*
<details><summary><i>Previously, daemonl (Damien Whitten) wrote…</i></summary><blockquote>

0770 != 770, and this matches the defaults in `os.Create`
</blockquote></details>

i dont see it in `os.Create`... the only reference to `Create` there is file creation, which is 0666?
___
*[main.go, line 124 at r1](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/1#-Lp_ke-UE6U2-9_YpZAE:-Lpa6ypk5-lVJgV9NG14:b5jnymq) ([raw file](https://github.com/dutyofcare/spa-version-proxy/blob/da859263acb10acbb37d128c8d2864435111ea67/main.go#L124)):*
<details><summary><i>Previously, daemonl (Damien Whitten) wrote…</i></summary><blockquote>

Theoretically immutable, but in practice possibly not. I've raised an issue for it, can discuss there. Do you want me to remove the TODO based on the issue?
</blockquote></details>

either; serves as a good marker, but it's also a duplicate that could hang around if the issue is closed

**Review by RickyCook — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/1)* status: all files reviewed, 3 unresolved discussions (waiting on @daemonl)

**Review by daemonl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/1)* status: all files reviewed, 3 unresolved discussions (waiting on @RickyCook)

___
*[main.go, line 92 at r1](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/1#-Lp_ihM55h4Zn_A19FMY:-Lpa85Ar8FSOTFTDtshP:bv1ij7a) ([raw file](https://github.com/dutyofcare/spa-version-proxy/blob/da859263acb10acbb37d128c8d2864435111ea67/main.go#L92)):*
<details><summary><i>Previously, RickyCook (Ricky Cook) wrote…</i></summary><blockquote>

i get that, but if you remove the conditional, there's no problem right? like no matter what, you just want to ensure that the name doesn't contain the path sep of your platform, and it doesn't matter if it's windows, nix, or anything else
</blockquote></details>

https://golang.org/src/net/http/fs.go?s=1882:1926#L58
___
*[main.go, line 95 at r1](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/1#-Lp_jODJANzazlF5iuFT:-Lpa8WOo02MI3f7hZ8VF:bv1ij7a) ([raw file](https://github.com/dutyofcare/spa-version-proxy/blob/da859263acb10acbb37d128c8d2864435111ea67/main.go#L95)):*
<details><summary><i>Previously, RickyCook (Ricky Cook) wrote…</i></summary><blockquote>

id suggest that we either explicitly dont support windows (my preference), or figure out what it does since it could be a security issue. i wouldnt say this should block this PR, but we should decide
</blockquote></details>

https://golang.org/src/net/http/fs.go?s=1882:1926#L58
___
*[main.go, line 98 at r1](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/1#-Lp_k2M_3wiO3Q0sL6dX:-LpawQ7iEw3Cr-7ZkEn3:b-jk3ql6) ([raw file](https://github.com/dutyofcare/spa-version-proxy/blob/da859263acb10acbb37d128c8d2864435111ea67/main.go#L98)):*
<details><summary><i>Previously, RickyCook (Ricky Cook) wrote…</i></summary><blockquote>

i dont see it in `os.Create`... the only reference to `Create` there is file creation, which is 0666?
</blockquote></details>

My bad, create does go with 0666 - which seems like an odd default, but I'll go with 0777 to match

**Review by RickyCook — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/1)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @daemonl and @RickyCook)

___
*[main.go, line 98 at r1](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/1#-Lp_k2M_3wiO3Q0sL6dX:-Lpaxw9G5iecsE1nmY5o:b53agx6) ([raw file](https://github.com/dutyofcare/spa-version-proxy/blob/da859263acb10acbb37d128c8d2864435111ea67/main.go#L98)):*
<details><summary><i>Previously, daemonl (Damien Whitten) wrote…</i></summary><blockquote>

My bad, create does go with 0666 - which seems like an odd default, but I'll go with 0777 to match
</blockquote></details>

yup... use `os.ModePerm` IMO: this gets reduced by the os's `umask`

**Review by daemonl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/1)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @RickyCook)

___
*[main.go, line 98 at r1](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/1#-Lp_k2M_3wiO3Q0sL6dX:-Lpay_4N617adhKn5x1j:bdidun2) ([raw file](https://github.com/dutyofcare/spa-version-proxy/blob/da859263acb10acbb37d128c8d2864435111ea67/main.go#L98)):*
<details><summary><i>Previously, RickyCook (Ricky Cook) wrote…</i></summary><blockquote>

yup... use `os.ModePerm` IMO: this gets reduced by the os's `umask`
</blockquote></details>

os.ModePerm == 0777 but really I don't care enough to argue

**Review by RickyCook — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/1)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @daemonl and @RickyCook)

___
*[main.go, line 92 at r1](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/1#-Lp_ihM55h4Zn_A19FMY:-LpazV3P4c7rqe5Xupus:bnbdswz) ([raw file](https://github.com/dutyofcare/spa-version-proxy/blob/da859263acb10acbb37d128c8d2864435111ea67/main.go#L92)):*
<details><summary><i>Previously, daemonl (Damien Whitten) wrote…</i></summary><blockquote>

https://golang.org/src/net/http/fs.go?s=1882:1926#L58
</blockquote></details>

linking to go code that may or may not be relevant to this particular situation is not an argument

**Review by RickyCook — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/1)* status: all files reviewed, 2 unresolved discussions (waiting on @daemonl and @RickyCook)

**Review by daemonl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/1)* status: all files reviewed, 2 unresolved discussions (waiting on @RickyCook)

___
*[main.go, line 92 at r1](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/1#-Lp_ihM55h4Zn_A19FMY:-LpazlNz-qCieYQ5gcG7:b-xr8k9t) ([raw file](https://github.com/dutyofcare/spa-version-proxy/blob/da859263acb10acbb37d128c8d2864435111ea67/main.go#L92)):*
<details><summary><i>Previously, RickyCook (Ricky Cook) wrote…</i></summary><blockquote>

linking to go code that may or may not be relevant to this particular situation is not an argument
</blockquote></details>

It's the go standard library implementation of opening a file from a HTTP provided path for the purpose of serving that file to the client

**Review by RickyCook — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/1)* status: all files reviewed, 2 unresolved discussions (waiting on @daemonl and @RickyCook)

___
*[main.go, line 92 at r1](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/1#-Lp_ihM55h4Zn_A19FMY:-Lpb-XWG8E9jlrZG8CbC:b-fla0m5) ([raw file](https://github.com/dutyofcare/spa-version-proxy/blob/da859263acb10acbb37d128c8d2864435111ea67/main.go#L92)):*
<details><summary><i>Previously, daemonl (Damien Whitten) wrote…</i></summary><blockquote>

It's the go standard library implementation of opening a file from a HTTP provided path for the purpose of serving that file to the client
</blockquote></details>

okay, this is where the problem is: `name` here is really a `urlPath` rather than a name per se, and will therefore always be unix-like. updating this identifier will make both this, and the next point more obvious that it's not got to do with the filesystem, but a url

**Review by daemonl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/1)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @RickyCook)

___
*[main.go, line 92 at r1](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/1#-Lp_ihM55h4Zn_A19FMY:-LpekOQB-q6_Qu1fhxd1:b-896fix) ([raw file](https://github.com/dutyofcare/spa-version-proxy/blob/da859263acb10acbb37d128c8d2864435111ea67/main.go#L92)):*
<details><summary><i>Previously, RickyCook (Ricky Cook) wrote…</i></summary><blockquote>

okay, this is where the problem is: `name` here is really a `urlPath` rather than a name per se, and will therefore always be unix-like. updating this identifier will make both this, and the next point more obvious that it's not got to do with the filesystem, but a url
</blockquote></details>

Done.

**Review by RickyCook — APPROVED** [review]
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/1)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
