### PR TITLE
Dev Proxy

### PR DESCRIPTION
**Pull request by daemonl**
Allows configuration of a proxy for api paths etc, similar to webpack dev server.

Not really appropriate or useful for deployed versions, but could aid in local development.

---
This change is [Reviewable](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/4)

### CODE REVIEW

**Review by RickyCook — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/4)* status: all files reviewed, 4 unresolved discussions (waiting on @daemonl)

___
*[main.go, line 269 at r1](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/4#-Lpa-9Y758Hq4QZje2yO:-Lpa-9Y758Hq4QZje2yP:b-p9wm4e) ([raw file](https://github.com/dutyofcare/spa-version-proxy/blob/bc10e2562723de877dc2568665c65272d53344f0/main.go#L269)):*
> ```Go
> 		return err
> 	}
> 	reqOut, err := http.NewRequest(reqIn.Method, reqIn.URL.String(), bytes.NewReader(body))
> ```

no way to do this with like `io.Copy(reqOut, reqIn.Body)`?
___
*[main.go, line 269 at r1](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/4#-Lpa-vEC2_6geEqHiuNv:-Lpa-vEC2_6geEqHiuNw:b6x16ma) ([raw file](https://github.com/dutyofcare/spa-version-proxy/blob/bc10e2562723de877dc2568665c65272d53344f0/main.go#L269)):*
> ```Go
> 		return err
> 	}
> 	reqOut, err := http.NewRequest(reqIn.Method, reqIn.URL.String(), bytes.NewReader(body))
> ```

i think it'd be good to use standard terms here if possible... eg `upstreamRequest`, `upstreamResponse`, `clientRequest`, `clientResponse`
___
*[main.go, line 275 at r1](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/4#-Lpa-K0R8_ZcdnOkDP0W:-Lpa-K0R8_ZcdnOkDP0X:b-6jnlfm) ([raw file](https://github.com/dutyofcare/spa-version-proxy/blob/bc10e2562723de877dc2568665c65272d53344f0/main.go#L275)):*
> ```Go
> 
> 	for k, vs := range reqIn.Header {
> 		if strings.ToLower(k) == "content-length" {
> ```

`content-length` shouldnt change right? why is it being excluded?
___
*[main.go, line 287 at r1](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/4#-Lpa-VFO1JyxgWiEYybS:-Lpa-VFO1JyxgWiEYybT:b-yuroso) ([raw file](https://github.com/dutyofcare/spa-version-proxy/blob/bc10e2562723de877dc2568665c65272d53344f0/main.go#L287)):*
> ```Go
> 		return err
> 	}
> 	reqIn.Body.Close()
> ```

body is already closed at the top of the function

**Review by daemonl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/4)* status: all files reviewed, 4 unresolved discussions (waiting on @daemonl and @RickyCook)

___
*[main.go, line 269 at r1](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/4#-Lpa-9Y758Hq4QZje2yO:-Lpa0l4WAc7_rmKh3Od4:b9bauut) ([raw file](https://github.com/dutyofcare/spa-version-proxy/blob/bc10e2562723de877dc2568665c65272d53344f0/main.go#L269)):*
<details><summary><i>Previously, RickyCook (Ricky Cook) wrote…</i></summary><blockquote>

no way to do this with like `io.Copy(reqOut, reqIn.Body)`?
</blockquote></details>

It should but things get a little odd, so using just copy doesn't actually work. If you think the memory usage in the dev proxy will be a problem, I can go back and make it work without reading if that's a blocker.
___
*[main.go, line 269 at r1](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/4#-Lpa-vEC2_6geEqHiuNv:-Lpa0zBf1L8QSDKt_Y-B:b-ii5pds) ([raw file](https://github.com/dutyofcare/spa-version-proxy/blob/bc10e2562723de877dc2568665c65272d53344f0/main.go#L269)):*
<details><summary><i>Previously, RickyCook (Ricky Cook) wrote…</i></summary><blockquote>

i think it'd be good to use standard terms here if possible... eg `upstreamRequest`, `upstreamResponse`, `clientRequest`, `clientResponse`
</blockquote></details>

There are many standards, all of them ambiguous because there's an alternate standard - is something unclear in reqOut, reqIn and resBack?
___
*[main.go, line 275 at r1](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/4#-Lpa-K0R8_ZcdnOkDP0W:-Lpa1PhKEF0lSucUTdvY:b-ge6nak) ([raw file](https://github.com/dutyofcare/spa-version-proxy/blob/bc10e2562723de877dc2568665c65272d53344f0/main.go#L275)):*
<details><summary><i>Previously, RickyCook (Ricky Cook) wrote…</i></summary><blockquote>

`content-length` shouldnt change right? why is it being excluded?
</blockquote></details>

Go adds it automatically, it probably doesn't matter, I think this one would win if go doesn't, but if go decides to chunk the response this will cause some interesting behavior - and go is able to to HTTP2 and other such things

**Review by daemonl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/4)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @RickyCook)

___
*[main.go, line 287 at r1](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/4#-Lpa-VFO1JyxgWiEYybS:-Lpa340L331maPU9cMAf:b-896fix) ([raw file](https://github.com/dutyofcare/spa-version-proxy/blob/bc10e2562723de877dc2568665c65272d53344f0/main.go#L287)):*
<details><summary><i>Previously, RickyCook (Ricky Cook) wrote…</i></summary><blockquote>

body is already closed at the top of the function
</blockquote></details>

Done.

**Review by RickyCook — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/4)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[main.go, line 269 at r1](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/4#-Lpa-9Y758Hq4QZje2yO:-Lpf9xtZ-0qFmWuvaVt0:bt6bw6) ([raw file](https://github.com/dutyofcare/spa-version-proxy/blob/bc10e2562723de877dc2568665c65272d53344f0/main.go#L269)):*
<details><summary><i>Previously, daemonl (Damien Whitten) wrote…</i></summary><blockquote>

It should but things get a little odd, so using just copy doesn't actually work. If you think the memory usage in the dev proxy will be a problem, I can go back and make it work without reading if that's a blocker.
</blockquote></details>

nope; just a question :)
___
*[main.go, line 275 at r1](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/4#-Lpa-K0R8_ZcdnOkDP0W:-LpfACjD-avq86PniK6k:bax4753) ([raw file](https://github.com/dutyofcare/spa-version-proxy/blob/bc10e2562723de877dc2568665c65272d53344f0/main.go#L275)):*
<details><summary><i>Previously, daemonl (Damien Whitten) wrote…</i></summary><blockquote>

Go adds it automatically, it probably doesn't matter, I think this one would win if go doesn't, but if go decides to chunk the response this will cause some interesting behavior - and go is able to to HTTP2 and other such things
</blockquote></details>

ah yeah true

**Pull request merged**
