### PR TITLE
Add Basic Logger

### PR DESCRIPTION
**Pull request by daemonl**
Adds a basic logger middleware

---
This change is [Reviewable](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/2)

### CODE REVIEW

**Review by RickyCook — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/2)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @daemonl and @RickyCook)

___
*[main.go, line 214 at r1](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/2#-Lp_lfMj6FRw1gvoJ7fN:-Lp_lfMk301EByWUAnCC:b8f56oq) ([raw file](https://github.com/dutyofcare/spa-version-proxy/blob/4131230ffc944612ec5a0b24767ca60110c10e3a/main.go#L214)):*
> ```Go
> 		recorder := &resRecorder{ResponseWriter: rw}
> 		next.ServeHTTP(recorder, req)
> 		log.Printf("%s %s => %d. In %f seconds. Path Rewrite to %s. Cache: %s",
> ```

could we format these like apache/nginx logs?
___
*[main.go, line 231 at r1](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/2#-Lp_lwK-8xw7kERacc2K:-Lp_lwK-8xw7kERacc2L:b-4po3dh) ([raw file](https://github.com/dutyofcare/spa-version-proxy/blob/4131230ffc944612ec5a0b24767ca60110c10e3a/main.go#L231)):*
> ```Go
> }
> 
> func (rr *resRecorder) Header() http.Header {
> ```

im not loving the name resRecorder. imo should just be `responseRecorder`
___
*[main.go, line 232 at r1](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/2#-Lp_m0jJCLZjLvPxQsqI:-Lp_m0jJCLZjLvPxQsqJ:bbtb68v) ([raw file](https://github.com/dutyofcare/spa-version-proxy/blob/4131230ffc944612ec5a0b24767ca60110c10e3a/main.go#L232)):*
> ```Go
> 
> func (rr *resRecorder) Header() http.Header {
> 	hdr := rr.ResponseWriter.Header()
> ```

same with `hdr`; much easier to follow if it's just `header`

**Review by RickyCook — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/2)* status: all files reviewed, 3 unresolved discussions (waiting on @daemonl)

**Review by daemonl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/2)* status: all files reviewed, 3 unresolved discussions (waiting on @RickyCook)

___
*[main.go, line 214 at r1](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/2#-Lp_lfMj6FRw1gvoJ7fN:-Lp_mX_TEPI1sPjZxr-z:b-a63xma) ([raw file](https://github.com/dutyofcare/spa-version-proxy/blob/4131230ffc944612ec5a0b24767ca60110c10e3a/main.go#L214)):*
<details><summary><i>Previously, RickyCook (Ricky Cook) wrote…</i></summary><blockquote>

could we format these like apache/nginx logs?
</blockquote></details>

They won't have the rewrite path, and I'm not keen on either dropping that or doing something which looks like apache style but isn't - maybe a different style altogether like JSON?
___
*[main.go, line 231 at r1](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/2#-Lp_lwK-8xw7kERacc2K:-Lp_mxeD11EF29G6udL9:bd2fioq) ([raw file](https://github.com/dutyofcare/spa-version-proxy/blob/4131230ffc944612ec5a0b24767ca60110c10e3a/main.go#L231)):*
<details><summary><i>Previously, RickyCook (Ricky Cook) wrote…</i></summary><blockquote>

im not loving the name resRecorder. imo should just be `responseRecorder`
</blockquote></details>

Disposition on this probably shouldn't be blocker, seems like a style preference.
___
*[main.go, line 232 at r1](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/2#-Lp_m0jJCLZjLvPxQsqI:-Lp_n81hALelN91xe6KV:bd2fioq) ([raw file](https://github.com/dutyofcare/spa-version-proxy/blob/4131230ffc944612ec5a0b24767ca60110c10e3a/main.go#L232)):*
<details><summary><i>Previously, RickyCook (Ricky Cook) wrote…</i></summary><blockquote>

same with `hdr`; much easier to follow if it's just `header`
</blockquote></details>

Disposition on this probably shouldn't be blocker, seems like a style preference.

**Review by RickyCook — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/2)* status: all files reviewed, 3 unresolved discussions (waiting on @daemonl and @RickyCook)

___
*[main.go, line 214 at r1](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/2#-Lp_lfMj6FRw1gvoJ7fN:-Lpa1Umy-gdr__DGGfeC:b-tb0h6p) ([raw file](https://github.com/dutyofcare/spa-version-proxy/blob/4131230ffc944612ec5a0b24767ca60110c10e3a/main.go#L214)):*
<details><summary><i>Previously, daemonl (Damien Whitten) wrote…</i></summary><blockquote>

They won't have the rewrite path, and I'm not keen on either dropping that or doing something which looks like apache style but isn't - maybe a different style altogether like JSON?
</blockquote></details>

apache logs still have a message section. loads of stuff adds the "lowest common denominator" in apache/nginx format (because it's an automatically parseable "http request", and add extra detail after like the rewrite. i agree, dropping the rewrite looses us really useful info

**Review by daemonl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/2)* status: all files reviewed, 3 unresolved discussions (waiting on @RickyCook)

___
*[main.go, line 214 at r1](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/2#-Lp_lfMj6FRw1gvoJ7fN:-Lpa4M2c16pRNR13wuKE:b-ekkkl6) ([raw file](https://github.com/dutyofcare/spa-version-proxy/blob/4131230ffc944612ec5a0b24767ca60110c10e3a/main.go#L214)):*
<details><summary><i>Previously, RickyCook (Ricky Cook) wrote…</i></summary><blockquote>

apache logs still have a message section. loads of stuff adds the "lowest common denominator" in apache/nginx format (because it's an automatically parseable "http request", and add extra detail after like the rewrite. i agree, dropping the rewrite looses us really useful info
</blockquote></details>

How would I log non-request things in apache format? What are we building which will parse this? Will it support other formats?

**Review by daemonl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/2)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @RickyCook)

___
*[main.go, line 214 at r1](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/2#-Lp_lfMj6FRw1gvoJ7fN:-LpekYOMBsAYDmGJqOWU:b-896fix) ([raw file](https://github.com/dutyofcare/spa-version-proxy/blob/4131230ffc944612ec5a0b24767ca60110c10e3a/main.go#L214)):*
<details><summary><i>Previously, daemonl (Damien Whitten) wrote…</i></summary><blockquote>

How would I log non-request things in apache format? What are we building which will parse this? Will it support other formats?
</blockquote></details>

Done.
___
*[main.go, line 231 at r1](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/2#-Lp_lwK-8xw7kERacc2K:-LpekZwaDEpCTw14EqAF:b-896fix) ([raw file](https://github.com/dutyofcare/spa-version-proxy/blob/4131230ffc944612ec5a0b24767ca60110c10e3a/main.go#L231)):*
<details><summary><i>Previously, daemonl (Damien Whitten) wrote…</i></summary><blockquote>

Disposition on this probably shouldn't be blocker, seems like a style preference.
</blockquote></details>

Done.
___
*[main.go, line 232 at r1](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/2#-Lp_m0jJCLZjLvPxQsqI:-Lpek_9N72gpyofmTSyO:b-896fix) ([raw file](https://github.com/dutyofcare/spa-version-proxy/blob/4131230ffc944612ec5a0b24767ca60110c10e3a/main.go#L232)):*
<details><summary><i>Previously, daemonl (Damien Whitten) wrote…</i></summary><blockquote>

Disposition on this probably shouldn't be blocker, seems like a style preference.
</blockquote></details>

Done.

**Review by RickyCook — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dutyofcare/spa-version-proxy/2)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
